openapi: 3.0.0
info:
  title: example_rails
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /v1/users:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
      description: ユーザ情報一覧
    parameters: []
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  point:
                    type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
  /v1/buys:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    item_name:
                      type: string
                    item_id:
                      type: integer
                    user_id:
                      type: integer
                    point:
                      type: integer
      description: 購入履歴一覧取得API
    post:
      summary: ''
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  item_id:
                    type: string
                  user_id:
                    type: string
                  point:
                    type: integer
      description: 購入API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                item_id:
                  type: integer
                user_id:
                  type: string
    parameters: []
  /v1/items:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    point:
                      type: integer
                    user_id:
                      type: string
      description: アイテムの出品
      requestBody: {}
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  point:
                    type: integer
                  user_id:
                    type: integer
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                  point:
                    type: integer
                  id:
                    type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name:
                  type: string
                point:
                  type: string
      description: 商品登録
    parameters: []
    put:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                  point:
                    type: integer
                  id:
                    type: integer
      description: 商品の更新
      parameters:
        - schema:
            type: integer
          in: query
          name: item_id
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                name:
                  type: string
                point:
                  type: integer
        description: ''
    delete:
      summary: ''
      responses:
        '200':
          description: OK
      description: 商品の削除
      parameters:
        - schema:
            type: integer
          in: query
          name: item_id
          description: ''
          required: true
components:
  schemas: {}
